# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='제목 없음', max_length=200),
        ),
    ]
